services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.5
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  terraform:
    image: hashicorp/terraform:1.9.5
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
    entrypoint: terraform